image: node:12-alpine
stages:
  - test
  - deploy

before_script:
  - yarn global add vsce
  - yarn

Deploy:
  script:
    - apk update && apk add git
    - git config user.email $GITLAB_USER_EMAIL
    - git config user.name $GITLAB_USER_NAME
    - yarn release
    - CUR_HEAD=$(git rev-parse HEAD)
    - git checkout master && git merge $CUR_HEAD
    - git push --follow-tags https://${GITLAB_USER_LOGIN}:${GL_PAT}@gitlab.com/jhechtf/git-angular.git origin master
    - vsce publish -p $PAT

  only:
    - master
  except:
    - tags
  when: manual